const zh = {"nav.work":"代表工作","nav.papers":"论文成果","nav.about":"关于我","nav.contact":"联系","hero.label":"机器人 · 运动规划 · 控制","hero.identity":"博士生 · 湖南大学","hero.title":"走向可靠的自主系统。<br>从理论到运动。","hero.intro":"研究自主机器人系统的运动规划与非线性控制，重点关注固定翼无人机。","hero.work":"查看代表工作 ↗","hero.contact":"联系我 →","media.hero":"研究，在运动中呈现","media.title":"飞行 · 制导 · 协同","media.pending":"研究视频待补充","media.caption":"通过演示了解我的研究","work.label":"研究与演示","work.title":"研究与演示。","work.intro":"围绕运动规划、学习与控制开展研究。这里将逐步补充演示视频和项目详情。","work.video1":"多机器人运动协调 · 论文补充视频","work.tag1":"运动协调 / 引导矢量场","work.title1":"安全运动，<br>协同系统。","work.desc1":"关注基于矢量场的制导方法，以及多机器人系统的安全分布式运动协调。","work.related":"相关论文","work.paper":"阅读论文 ↗","work.video2":"固定翼无人机实验演示","work.tag2":"空中机器人 / 制导与控制","work.title2":"面向自主飞行。","work.desc2":"研究自主固定翼无人机系统的运动规划、制导与控制。","work.forthcoming":"项目详情待补充","work.details":"后续将结合演示介绍方法、个人贡献和实验结果。","work.video3":"机器人规划仿真演示","work.tag3":"学习 / 机器人运动规划","work.title3":"学习如何找到路径。","work.desc3":"探索基于扩散模型的机器人路径规划，以及非线性系统建模与控制。","papers.label":"论文成果","papers.title":"代表论文。","papers.note":"完整作者列表和出版信息待补充。","about.caption":"李政 / 湖南大学","about.label":"个人介绍","about.title":"关于我","about.bio":"我目前在湖南大学人工智能与机器人学院攻读博士学位。2024 年毕业于福州大学梅努斯国际工程学院机器人与智能器件专业，获工学学士学位。","about.research":"研究兴趣包括固定翼无人机系统、引导矢量场、基于扩散模型的机器人规划，以及非线性系统建模与控制。","about.cv":"个人简历 · 待补充","contact.label":"联系方式","contact.title":"一起探讨机器人研究。","contact.desc":"欢迎学术交流、科研合作与职业机会沟通。","footer":"机器人与自主系统","top":"返回顶部 ↑"};
zh["work.openvideo"] = "打开完整视频 ↗";
zh["profile.school"]="人工智能与机器人学院";
zh["profile.location"]="中国 · 长沙";
zh["profile.focus"]="研究重点";
zh["profile.topics"]="空中机器人<br>运动规划<br>非线性控制";
Object.assign(zh,{"copy.home": "主页", "copy.projects": "项目", "copy.role": "博士生", "copy.university": "湖南大学", "copy.bio": "你好！我是<strong>李政（Zheng Li）</strong>，目前在<strong>湖南大学人工智能与机器人学院</strong>攻读博士学位。2024 年毕业于福州大学梅努斯国际工程学院机器人与智能器件专业，获工学学士学位。", "copy.paperintro": "我的研究包括基于矢量场的多机器人运动协调。下方展示代表论文及其补充演示视频。", "copy.interests": "研究方向", "copy.direction": "研究方向", "copy.gvf": "引导矢量场", "copy.gvfdesc": "基于引导矢量场的制导，以及多机器人系统的安全分布式运动协调。", "copy.diffusion": "基于扩散模型的机器人规划", "copy.diffusiondesc": "复杂环境中的学习型路径规划与智能导航。", "copy.nonlinear": "非线性系统", "copy.nonlineardesc": "复杂动态系统的建模、稳定性分析与控制。", "copy.vision": "研究自主机器人系统的规划与控制方法，关注复杂环境中的可靠运动。", "copy.video": "视频 ↓", "copy.watch": "观看演示 →", "copy.coordination": "基于矢量场的运动协调", "copy.supplement": "科研项目 · 补充视频", "copy.uav": "固定翼无人机系统", "copy.ongoing": "研究方向"});
const elements = [...document.querySelectorAll('[data-t]')];
const en = Object.fromEntries(elements.map(el => [el.dataset.t, el.innerHTML]));
let language = 'en';
const languageButton = document.querySelector('#language');
languageButton.addEventListener('click', () => {
 language = language === 'en' ? 'zh' : 'en';
 document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en';
 elements.forEach(el => { el.innerHTML = (language === 'zh' ? zh : en)[el.dataset.t]; });
 languageButton.textContent = language === 'en' ? '中文' : 'EN';
});
const menu = document.querySelector('#menu');
const nav = document.querySelector('#navigation');
menu.addEventListener('click', () => { const open = nav.classList.toggle('open'); menu.setAttribute('aria-expanded', String(open)); });
nav.querySelectorAll('a').forEach(a => a.addEventListener('click', () => { nav.classList.remove('open'); menu.setAttribute('aria-expanded','false'); }));
